# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from utility.MyLabel import DraggableDroppableLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label1.setFont(font)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.label3 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label3.setFont(font)
        self.label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label3.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 3, 1, 1)
        self.label4 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label4.setFont(font)
        self.label4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label4.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 1, 0, 1, 1)
        self.label2 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label2.setFont(font)
        self.label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 1, 1, 1)
        self.label5 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label5.setFont(font)
        self.label5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label5.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.gridLayout.addWidget(self.label5, 1, 1, 1, 1)
        self.label6 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label6.setFont(font)
        self.label6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label6.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.gridLayout.addWidget(self.label6, 1, 3, 1, 1)
        self.label7 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label7.setFont(font)
        self.label7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label7.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName("label7")
        self.gridLayout.addWidget(self.label7, 2, 0, 1, 1)
        self.label8 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label8.setFont(font)
        self.label8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label8.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 2, 1, 1, 1)
        self.label9 = DraggableDroppableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label9.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label9.setFont(font)
        self.label9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label9.setAlignment(QtCore.Qt.AlignCenter)
        self.label9.setObjectName("label9")
        self.gridLayout.addWidget(self.label9, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startBtn.setFont(font)
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startBtn.setIcon(icon)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.endBtn = QtWidgets.QPushButton(self.centralwidget)
        self.endBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.endBtn.setFont(font)
        self.endBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.endBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.endBtn.setIcon(icon1)
        self.endBtn.setObjectName("endBtn")
        self.horizontalLayout.addWidget(self.endBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.randomBrn = QtWidgets.QPushButton(self.centralwidget)
        self.randomBrn.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.randomBrn.setFont(font)
        self.randomBrn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.randomBrn.setObjectName("randomBrn")
        self.verticalLayout_2.addWidget(self.randomBrn)
        self.loadImageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageBtn.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.loadImageBtn.setFont(font)
        self.loadImageBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loadImageBtn.setObjectName("loadImageBtn")
        self.verticalLayout_2.addWidget(self.loadImageBtn)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 400))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 398))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.textLabel.setText("")
        self.textLabel.setObjectName("textLabel")
        self.gridLayout_3.addWidget(self.textLabel, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Puzzle"))
        self.label1.setText(_translate("MainWindow", "1"))
        self.label3.setText(_translate("MainWindow", "3"))
        self.label4.setText(_translate("MainWindow", "4"))
        self.label2.setText(_translate("MainWindow", "2"))
        self.label5.setText(_translate("MainWindow", "5"))
        self.label6.setText(_translate("MainWindow", "6"))
        self.label7.setText(_translate("MainWindow", "7"))
        self.label8.setText(_translate("MainWindow", "8"))
        self.label9.setText(_translate("MainWindow", "9"))
        self.randomBrn.setText(_translate("MainWindow", "Random"))
        self.loadImageBtn.setText(_translate("MainWindow", "Load Image"))
