# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 3, 1, 1)
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 1, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 1, 1, 1)
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setObjectName("label5")
        self.gridLayout.addWidget(self.label5, 1, 1, 1, 1)
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setObjectName("label6")
        self.gridLayout.addWidget(self.label6, 1, 3, 1, 1)
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setObjectName("label7")
        self.gridLayout.addWidget(self.label7, 2, 0, 1, 1)
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 2, 1, 1, 1)
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setObjectName("label9")
        self.gridLayout.addWidget(self.label9, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.endBtn = QtWidgets.QPushButton(self.centralwidget)
        self.endBtn.setObjectName("endBtn")
        self.horizontalLayout.addWidget(self.endBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.randomBrn = QtWidgets.QPushButton(self.centralwidget)
        self.randomBrn.setObjectName("randomBrn")
        self.verticalLayout_2.addWidget(self.randomBrn)
        self.loadImageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageBtn.setObjectName("loadImageBtn")
        self.verticalLayout_2.addWidget(self.loadImageBtn)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "TextLabel"))
        self.label3.setText(_translate("MainWindow", "TextLabel"))
        self.label4.setText(_translate("MainWindow", "TextLabel"))
        self.label2.setText(_translate("MainWindow", "TextLabel"))
        self.label5.setText(_translate("MainWindow", "TextLabel"))
        self.label6.setText(_translate("MainWindow", "TextLabel"))
        self.label7.setText(_translate("MainWindow", "TextLabel"))
        self.label8.setText(_translate("MainWindow", "TextLabel"))
        self.label9.setText(_translate("MainWindow", "TextLabel"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.endBtn.setText(_translate("MainWindow", "End"))
        self.randomBrn.setText(_translate("MainWindow", "Random"))
        self.loadImageBtn.setText(_translate("MainWindow", "Load Image"))

        item_list = ["BFS", "DFS", "A*", "IDS"]
        self.comboBox.addItems(item_list)
